FROM eclipse-temurin:21-jdk AS build
WORKDIR /app

COPY gradlew settings.gradle gradle.properties build.gradle ./
COPY gradle gradle
RUN chmod +x gradlew

COPY src src
RUN ./gradlew installDist --no-daemon

FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app

COPY --from=build /app/build/install/app ./

ENTRYPOINT ["./bin/app"]
